const OFFLINE_AFTER_MS = Number(process.env.OFFLINE_AFTER_MS || 15000);
const WINDOW_MS = 60_000;
const HISTORY_MAX = 2000;
const TRANSITIONS_MAX = 50;

const devices = new Map();
const seen = new Map();

function now() {
  return Date.now();
}

function parseTs(ts) {
  const value = Date.parse(ts);
  return Number.isFinite(value) ? value : NaN;
}

function stableKey(msg) {
  // Device timestamps are generated by the tracker. Same device + same timestamp
  // represents the same reading for this exercise.
  return `${msg.deviceId}|${msg.ts}`;
}

function getDevice(id) {
  if (!devices.has(id)) {
    devices.set(id, {
      deviceId: id,
      latest: null,
      readings: [],
      transitions: [],
      totalDistanceMeters: 0,
      lastOdometerMeters: null,
      lastAcceptedTsMs: null,
      lastSeenWallMs: 0,
      lastState: null,
      stateSinceWallMs: 0,
      connected: false,
      resetCount: 0,
      duplicateCount: 0,
      outOfOrderCount: 0
    });
  }
  return devices.get(id);
}

function pruneSeen() {
  const cutoff = now() - 10 * 60_000;
  for (const [k, t] of seen) {
    if (t < cutoff) seen.delete(k);
  }
}

export function ingest(msg) {
  const d = getDevice(msg.deviceId);
  const tsMs = parseTs(msg.ts);
  if (!Number.isFinite(tsMs)) return { accepted: false, reason: "invalid_timestamp" };

  const key = stableKey(msg);
  if (seen.has(key)) {
    d.duplicateCount++;
    stats.deduped++;
    return { accepted: false, reason: "duplicate" };
  }
  seen.set(key, now());

  const wall = now();
  d.lastSeenWallMs = wall;
  d.connected = true;

  // Keep readings for rolling calculations, including valid out-of-order readings.
  // A duplicate is removed before this point.
  d.readings.push({
    tsMs,
    receivedWallMs: wall,
    state: msg.state,
    speedKph: Number(msg.speedKph) || 0,
    batteryPct: Number(msg.batteryPct) || 0,
    odometerMeters: Number(msg.odometerMeters) || 0,
    routeId: msg.routeId,
    faults: Array.isArray(msg.faults) ? msg.faults : []
  });

  if (d.readings.length > HISTORY_MAX) d.readings.splice(0, d.readings.length - HISTORY_MAX);

  if (d.lastAcceptedTsMs !== null && tsMs < d.lastAcceptedTsMs) {
    d.outOfOrderCount++;
    stats.outOfOrder++;
    // It is useful for aggregates/history, but must not overwrite latest.
    pruneSeen();
    return { accepted: true, reason: "out_of_order" };
  }

  const previousState = d.lastState;
  const previousOdo = d.lastOdometerMeters;

  if (previousOdo !== null) {
    const delta = Number(msg.odometerMeters) - previousOdo;
    if (delta >= 0) {
      d.totalDistanceMeters += delta;
    } else {
      // Counter reset/reboot. Never report negative travelled distance.
      d.resetCount++;
      stats.counterResets++;
      // The new odometer value is treated as a fresh counter. We do not add a
      // negative delta; subsequent positive deltas will count normally.
    }
  }

  d.lastOdometerMeters = Number(msg.odometerMeters) || 0;
  d.lastAcceptedTsMs = tsMs;
  d.latest = {
    deviceId: msg.deviceId,
    ts: msg.ts,
    state: msg.state,
    speedKph: Number(msg.speedKph) || 0,
    batteryPct: Number(msg.batteryPct) || 0,
    odometerMeters: Number(msg.odometerMeters) || 0,
    routeId: msg.routeId,
    faults: Array.isArray(msg.faults) ? msg.faults : []
  };

  if (previousState !== null && previousState !== msg.state) {
    d.transitions.push({
      from: previousState,
      to: msg.state,
      ts: msg.ts
    });
    if (d.transitions.length > TRANSITIONS_MAX) {
      d.transitions.splice(0, d.transitions.length - TRANSITIONS_MAX);
    }
  }
  if (previousState === null) {
    d.stateSinceWallMs = wall;
  }
  d.lastState = msg.state;

  stats.received++;
  pruneSeen();
  return { accepted: true, reason: "accepted" };
}

export function refreshOnlineStatus() {
  const t = now();
  for (const d of devices.values()) {
    d.connected = Boolean(d.lastSeenWallMs && t - d.lastSeenWallMs <= OFFLINE_AFTER_MS);
  }
}

function rolling(d, windowMs = WINDOW_MS) {
  const cutoff = Date.now() - windowMs;
  const rs = d.readings.filter(r => r.receivedWallMs >= cutoff);

  if (!rs.length) {
    return { avgSpeedKph: 0, avgBatteryPct: d.latest?.batteryPct ?? 0, movingPct: 0, distanceLast60sMeters: 0 };
  }

  const avgSpeedKph = rs.reduce((a, r) => a + r.speedKph, 0) / rs.length;
  const avgBatteryPct = rs.reduce((a, r) => a + r.batteryPct, 0) / rs.length;

  // Integrate wall-clock intervals using the chronological readings we have.
  const ordered = [...rs].sort((a, b) => a.receivedWallMs - b.receivedWallMs);
  let movingMs = 0;
  let distance = 0;
  for (let i = 1; i < ordered.length; i++) {
    const a = ordered[i - 1];
    const b = ordered[i];
    const dt = Math.max(0, Math.min(b.receivedWallMs - a.receivedWallMs, windowMs));
    if (a.state === "MOVING") movingMs += dt;
    distance += Math.max(0, (a.speedKph * dt) / 3.6);
  }
  const first = ordered[0];
  const last = ordered[ordered.length - 1];
  const tail = Math.max(0, Math.min(Date.now() - last.receivedWallMs, windowMs));
  if (last.state === "MOVING") movingMs += tail;

  return {
    avgSpeedKph,
    avgBatteryPct,
    movingPct: Math.min(100, (movingMs / windowMs) * 100),
    distanceLast60sMeters: distance
  };
}

export function deviceSummary(d) {
  const r = rolling(d);
  return {
    deviceId: d.deviceId,
    state: d.connected ? (d.latest?.state ?? "OFF") : "OFFLINE",
    speedKph: d.latest?.speedKph ?? 0,
    batteryPct: d.latest?.batteryPct ?? 0,
    movingPct: r.movingPct,
    distanceLast60sMeters: r.distanceLast60sMeters,
    totalDistanceMeters: d.totalDistanceMeters,
    secondsSinceLastMessage: d.lastSeenWallMs ? Math.floor((Date.now() - d.lastSeenWallMs) / 1000) : null,
    lastMessage: d.latest?.ts ?? null,
    faults: d.latest?.faults ?? []
  };
}

export function allDevices() {
  refreshOnlineStatus();
  return [...devices.values()].map(deviceSummary);
}

export function getDetails(id) {
  refreshOnlineStatus();
  const d = devices.get(id);
  if (!d) return null;
  const r = rolling(d);
  return {
    ...deviceSummary(d),
    averageSpeedKph60s: r.avgSpeedKph,
    averageBatteryPct60s: r.avgBatteryPct,
    history: d.readings.slice(-200).sort((a, b) => a.tsMs - b.tsMs),
    stateTransitions: d.transitions.slice(-50)
  };
}

export function getHistory(id, windowMs) {
  const d = devices.get(id);
  if (!d) return null;
  const cutoff = Date.now() - windowMs;
  return d.readings.filter(r => r.receivedWallMs >= cutoff).sort((a, b) => a.tsMs - b.tsMs);
}

export const stats = {
  received: 0,
  deduped: 0,
  outOfOrder: 0,
  counterResets: 0,
  reconnects: 0,
  startedAt: Date.now()
};

export function getStats() {
  refreshOnlineStatus();
  return {
    ...stats,
    devices: devices.size,
    online: [...devices.values()].filter(d => d.connected).length,
    uptimeSeconds: Math.floor((Date.now() - stats.startedAt) / 1000)
  };
}
